### ISSUE TITLE
Disabled `agent_sheet` still loads

### ISSUE THREAD

**Issue by rubaboo** [MrOtherGuy/fx-autoconfig#62]
If I remove `// @stylemode      agent_sheet`, then it's only loaded when enabled.

**Comment by MrOtherGuy** [comment]
Wow, how come nobody has noticed that before. Anyway, thanks for reporting - this is fixed in 0.10.4

**Comment by rubaboo** [comment]
Thanks. BTW, I wanted to share – 0.10.3 (the previous release) fixed a random startup error I kept getting about 3 out of 5 restarts. (Which was frustrating but caused me to learn fx-autoconfig and improve my scripts.)

**Comment by MrOtherGuy** [comment]
Out of interest, how did the error you were experiencing manifest? Like, was the browser completely unusable or what? Also regarding the "enable workaround" thing, from 0.10.3 onwards we don't show that button anymore because the workaround wouldn't do anything in Firefox 134 anyway.

Chances are that the error might have been caused essetially by one of your scripts executing too early during startup. If such were the case, then in my opinion the correct thing to do would be to delay execution until the startup is complete. So you could have a window scoped script like this:

```js
function runMeOnStartupFinished(){
 console.log("startup is complete") 
// your logic here
}
UC_API.Runtime.startupFinished().then(runMeOnStartup)
```

**Comment by rubaboo** [comment]
> was the browser completely unusable or what?

Actually, it was quite the opposite. There was no ill effect that I could see, everything continued working. It was just annoying and making me me think my scripts are bad.

Yup, I did delay like you suggest and more. Even added a crazy long timeout.
Here's how my `.sys.mjs` script looks like (and I was still getting the error):
```js
// ==UserScript==
// @name                 sample script
// @namespace        rubaboo
// @version              1.0
// @description          Do it
// ==/UserScript==

import { Runtime, Windows } from "chrome://userchromejs/content/uc_api.sys.mjs";
let ms = 8000;

Runtime.startupFinished().then(() => {
  /* each existing browser window and
     each window created subsequently */
  Windows.forEach( (d,ws) => ws.setTimeout(doit, ms, ws), true );
  Windows.onCreated(  wc  => wc.setTimeout(doit, ms, wc)        );
});

/* ----  Functions  ------------------------ */

function doit(w) {
if (Windows.isBrowserWindow(w)) {
Windows.waitWindowLoading(w).then(wi => {
…
```

**Comment by MrOtherGuy** [comment]
> Actually, it was quite the opposite. There was no ill effect that I could see, everything continued working. It was just annoying and making me me think my scripts are bad.

In the past the error could also manifest if it happened to be the case that the window was completely occluded by some other window during startup. But that shouldn't be the case anymore for quite some time. Checking browser console will probably yield more clues.

But yes, your logic does need to be inside the promise then callback - although if the rest of your stuff does not need to wait for startup then that can be written in a synchronous form:

```js
 function runMeOnStartupFinished(){
 console.log("startup is complete, safe to proceed") 
}
UC_API.Runtime.startupFinished().then(runMeOnStartupFinished);

// Proceeding with my logic
console.log("hi")

```

Now this first creates the promise - the creation itself is synchronous. The immediately afterwards the console.log("hi") will happen. Then at some point in the future the promise resolves and `runMeOnStartupFinished` gets executed.

**Comment by MrOtherGuy** [comment]
The `await` keyword does make the engine handle async functions sort of like synchronous ones:

```js
await UC_API.Runtime.startupFinished();

// Proceeding with my logic
console.log("hi")
```

In theory this would make the javascript engine wait for startup, and only then proceed to the `console.log("hi")`
However, this would now be a top-level-await since it is not inside an asynchronous function. I have not tried what would happen here, but my guess is that the startup would just stall indefinitely. .sys.mjs scripts are loaded and executed immediately by the loader, so if a script decides to await something, then the startup can never actually proceed.
